[package]
name = "multisig_program"
version = "0.1.0"
edition = "2024"

[build-dependencies]
risc0-binfmt = "=3.0.4"

[dependencies]
multisig_core = { path = "../multisig_core" }
nssa_core.workspace = true
spel-framework = { git = "https://github.com/jimmy-claw/spel", branch = "jimmy/pre-tx-hook" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
borsh.workspace = true
risc0-zkvm.workspace = true
